version: "3"

services:
    app:
        build: .
        hostname: "rws"
        container_name: "rws"
        ports:
            - "3000:3000"
            - "8080:8080"
        volumes:
            - .:/opt/app/rws